import type { NextPage } from 'next'
import Head from 'next/head'
//import { getAuth, signInWithEmailAndPassword } from "firebase/auth"

//const auth = getAuth();

/* const handleLogin = () => {
    signInWithEmailAndPassword(auth, "a1zan.zlender@gmail.com", "12345678!Aa")
    .then((userCredential) => {
        const user = userCredential.user;

        console.log(user)
    })
    .then((nvm) => {
        console.log("THIS IS ME")
        console.log(auth.currentUser)
    })
    .catch((error) => {
        const errorCode = error.code;
        const errorMessage = error.message;

        console.log(`Error code ${errorCode}: ${errorMessage}`)
    })
} */
const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {
        
    }
      <div className={"bg-green-700 h-screen w-full flex"}>
        <h1 className={"mx-auto my-auto"}>Nada svake mame</h1>

        {/*<button onClick={handleLogin} className={"mx-auto my-auto h-12 w-40 text-white rounded-md bg-blue-700"}>This is a sexy button</button>*/}

      </div>

    </div>
  )
}

export default Login
